In [1]:
import pandas as pd
import datetime as dt

In [2]:
df = pd.read_csv(r'PAH_April_2022.csv', encoding='latin1')

In [3]:
df['Date'] = pd.to_datetime(df['Visit Date']).dt.day

In [4]:
df['day'] = pd.to_datetime(df['Visit Date']).dt.dayofweek

In [6]:
df['day'].value_counts()

5    2736
0    2389
4    2368
1    1996
2    1840
3    1710
6    1118
Name: day, dtype: int64

In [8]:
df.head(100)

,Visit Date,Visit Date_01,HIN No.,Patient Name,Patient_Phone1,Age,Age Group,Gender,Category,Disease,...,Medical History,Pathology/Lab Reports,Radiology Reports,Panchkarma,Panchkarma Sheet,Shatkarma Sheet,Feedback by patient,Others,Date,day
0,2022-04-01,01-04-2022,1.648802e+10,VIBHA NAYYAR,7.760513e+09,82,66-100,Female,MISCELLANEOUS DISORDERS,AADIBALPRIVRITTA VIKARA/ INBORN ERRORS OF META...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
1,2022-04-01,01-04-2022,1.648802e+10,VIBHA NAYYAR,7.760513e+09,82,66-100,Female,CANCER,KARKATARBUD / CANCER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
2,2022-04-01,01-04-2022,1.601974e+10,MADHU BHANDARI,9.639882e+09,42,36-50,Female,MUSCULO-SKELETAL DISORDERS,AAMA-VATA / RHEUMATOID ARTHRITIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
3,2022-04-01,01-04-2022,1.639805e+10,SUMAN VERMA,9.719547e+09,45,36-50,Female,MUSCULO-SKELETAL DISORDERS,AAMA-VATA / RHEUMATOID ARTHRITIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
4,2022-04-01,01-04-2022,1.639805e+10,ANITA,9.837252e+09,43,36-50,Female,MUSCULO-SKELETAL DISORDERS,AAMA-VATA / RHEUMATOID ARTHRITIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-04-01,01-04-2022,1.648790e+10,DAYALSINGH RAWAT,9.560808e+09,69,66-100,Male,KIDNEY DISORDERS,CHRONIC RENAL FAILURE(CRF) / CHRONIC RENAL FAI...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
96,2022-04-01,01-04-2022,1.648798e+10,MADHUR VERMA,7.017355e+09,48,36-50,Male,KIDNEY DISORDERS,CHRONIC RENAL FAILURE(CRF) / CHRONIC RENAL FAI...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
97,2022-04-01,01-04-2022,1.648811e+10,SHRI GOPAL DHAR BADGAIYAN,8.085821e+09,51,51-65,Male,KIDNEY DISORDERS,CHRONIC RENAL FAILURE(CRF) / CHRONIC RENAL FAI...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
98,2022-04-01,01-04-2022,1.645675e+10,POONAM BANSAL,9.650212e+09,51,51-65,Female,KIDNEY DISORDERS,CHRONIC RENAL FAILURE(CRF) / CHRONIC RENAL FAI...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
99,2022-04-01,01-04-2022,1.647082e+10,MANJU RANI,9.548024e+09,58,51-65,Female,KIDNEY DISORDERS,CHRONIC RENAL FAILURE(CRF) / CHRONIC RENAL FAI...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4