In [1]:
import pandas as pd
import datetime as dt

In [8]:
df = pd.read_csv(r'00_Patient Feedback Report Jan-August_2022.csv', encoding='latin1')

In [9]:
df['year'] = pd.DatetimeIndex(df['Date']).year

In [10]:
df['month'] = pd.DatetimeIndex(df['Date']).month

In [11]:
df.head(10)

,Date,Date_01,HIN No.,Patient Name,Address,Contact No.,Email,Age,Age Group,Gender,...,Following Diet Chart,Following Additional Advices,Medicine_Status,Relief %,Reason,Remarks,Status,Other,year,month
0,2022-01-01,01-01-2022,16309059289,BHANUVIR SINGH,VILL-PREMPUR ANANDIPUR PO-BILHANA,9.760293e+09,NaN,31,21-35,Male,...,NaN,,Medicine Continue,0,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
1,2022-01-01,01-01-2022,16309059289,BHANUVIR SINGH,VILL-PREMPUR ANANDIPUR PO-BILHANA,9.760293e+09,NaN,31,21-35,Male,...,NaN,,Medicine Continue,40,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
2,2022-01-01,01-01-2022,16340136306,DHARM VIR SINGH,VILL- ETOLI,8.765585e+09,NaN,37,36-50,Male,...,NaN,,Medicine Continue,0,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
3,2022-01-01,01-01-2022,16340136306,DHARM VIR SINGH,VILL- ETOLI,8.765585e+09,NaN,37,36-50,Male,...,NaN,,Medicine Continue,0,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
4,2022-01-01,01-01-2022,16340136306,DHARM VIR SINGH,VILL- ETOLI,8.765585e+09,NaN,37,36-50,Male,...,NaN,,Medicine Continue,30,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
5,2022-01-01,01-01-2022,16340136306,DHARM VIR SINGH,VILL- ETOLI,8.765585e+09,NaN,37,36-50,Male,...,NaN,,Medicine Continue,30,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
6,2022-01-01,01-01-2022,16407581452,SATYAPAL SINGH MALIK,PARSAUL,9.457066e+09,NaN,57,51-65,Male,...,NaN,,Medicine Continue,0,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
7,2022-01-01,01-01-2022,16407581452,SATYAPAL SINGH MALIK,PARSAUL,9.457066e+09,NaN,57,51-65,Male,...,NaN,,Medicine Continue,30,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
8,2022-01-01,01-01-2022,16410115650,KUSHAL KUMAR,BHIRI BEGAMPUR OPP PATNA SAHIB RAILWAY STN,9.334864e+09,NaN,30,21-35,Male,...,NaN,,Medicine Continue,30,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1
9,2022-01-01,01-01-2022,16410110927,RADHESHYAM YADAV,NANDNA WARD EAST BARHAJ BAZAR,8.922043e+09,NaN,45,36-50,Male,...,NaN,,Medicine Continue,0,NaN,During feedback calling patient stated that he...,NaN,NaN,2022,1

In [12]:
df.to_csv("Jan_august_2022.csv")

In [13]:
df.groupby(['Medicine_Status', 'month']).size()

Medicine_Status       month
Cured                 1         129
                      2          93
                      3         127
                      4         104
                      5         118
                      6         131
                      7         124
                      8         131
Medicine Continue     1        3222
                      2        3728
                      3        6652
                      4        5108
                      5        5658
                      6        5415
                      7        4066
                      8        4232
Medicine Discontinue  1         677
                      2         740
                      3         982
                      4         846
                      5         918
                      6        1044
                      7         761
                      8         883
Other                 1          13
                      2          10
                      3          37
                      4          26
                      5          30
                      6          43
                      7          29
                      8          31
Patient Death         1         100
                      2          58
                      3          81
                      4          67
                      5          72
                      6          58
                      7          57
                      8          76
Pending               2           2
                      8           1
dtype: int64

In [14]:
df.groupby(['month', 'Medicine_Status']).size()

month  Medicine_Status
1      Cured                    129
       Medicine Continue       3222
       Medicine Discontinue     677
       Other                     13
       Patient Death            100
2      Cured                     93
       Medicine Continue       3728
       Medicine Discontinue     740
       Other                     10
       Patient Death             58
       Pending                    2
3      Cured                    127
       Medicine Continue       6652
       Medicine Discontinue     982
       Other                     37
       Patient Death             81
4      Cured                    104
       Medicine Continue       5108
       Medicine Discontinue     846
       Other                     26
       Patient Death             67
5      Cured                    118
       Medicine Continue       5658
       Medicine Discontinue     918
       Other                     30
       Patient Death             72
6      Cured                    131
       Medicine Continue       5415
       Medicine Discontinue    1044
       Other                     43
       Patient Death             58
7      Cured                    124
       Medicine Continue       4066
       Medicine Discontinue     761
       Other                     29
       Patient Death             57
8      Cured                    131
       Medicine Continue       4232
       Medicine Discontinue     883
       Other                     31
       Patient Death             76
       Pending                    1
dtype: int64

In [15]:
df.groupby(['month', 'Medicine_Status']).size().to_csv("medicie_status.csv")